package com.alyokaz.aktorrent.server.message;

public enum MessageType {
    REQUEST_FILENAMES, REQUEST_PIECES, END, REQUEST_PIECE, REQUEST_PEERS, GET_COMPLETED_FILES, REQUSET_FILE_INFOS, REQUEST_AVAILABLE_FILES
}
